/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'ap-northeast-1',
    aws_cognito_identity_pool_id: 'ap-northeast-1:bb858f00-070b-47e0-ad32-4986896325ad',
    aws_cognito_region: 'ap-northeast-1',
    aws_user_pools_id: 'ap-northeast-1_xw9GE5uIk',
    aws_user_pools_web_client_id: '7c4n84kpf5n0mmkr2rdp1id33b',
    oauth: {},
    aws_appsync_graphqlEndpoint: 'https://og46ahqkt5ckln3qx2nwxgkudi.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    aws_appsync_region: 'ap-northeast-1',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};


export default awsmobile;
